import type { Locale } from '$lib/site';

export const ui = {
  ko: {
    personalRecord: '개인 기록',
    timeline: '이력',
    projects: '프로젝트',
    outputs: '산출물',
    knowledge: '지식',
    skipToContent: '본문으로 건너뛰기',
    primaryNavigation: '주요 메뉴',
    languageSelection: '언어 선택',
    homeEyebrow: 'PERSONAL RECORD',
    now: '현재',
    selectedProjects: '선별 프로젝트',
    recentOutputs: '최근 산출물',
    allTimeline: '전체 이력',
    allProjects: '전체 프로젝트',
    allOutputs: '전체 산출물',
    timelineDescription: '확인된 역할과 활동을 시간의 흐름에 따라 정리합니다.',
    projectsDescription: '맡은 역할, 과정, 결과가 확인된 작업을 선별해 기록합니다.',
    outputsDescription: '소프트웨어, 논문, 발표 등 작업에서 나온 구체적인 결과물입니다.',
    knowledgeTitle: '설명과 학습 기록은 Tokamak에 있습니다.',
    knowledgeDescription: '프로젝트가 무엇을 했는지는 여기서, 그 과정에서 정리한 지식은 Tokamak에서 읽을 수 있습니다.',
    visitKnowledge: 'Tokamak에서 지식 탐색',
    role: '역할',
    contributions: '기여',
    outcomes: '결과',
    relatedOutputs: '관련 산출물',
    relatedTimeline: '관련 이력',
    relatedKnowledge: '관련 지식 · Tokamak',
    atAGlance: '한눈에 보기',
    period: '기간',
    status: '상태',
    present: '현재',
    sourceLanguage: '원문',
    openProject: '프로젝트 보기',
    externalLink: '외부 링크',
    profileApprovalRequired: '개인 콘텐츠 공개 확인이 필요합니다.',
    profileApprovalDescription: '구조와 검증기는 준비되었지만, 확인되지 않은 이력과 프로젝트는 공개하지 않습니다.',
    backToProjects: '프로젝트로 돌아가기',
    noPublishedProjects: '공개 승인된 프로젝트가 없습니다.',
    noPublishedTimeline: '공개 승인된 이력이 없습니다.',
    noPublishedOutputs: '공개 승인된 산출물이 없습니다.',
    servedThrough: 'GitHub Pages 정적 사이트',
    lifecycle: {
      planned: '예정',
      active: '진행 중',
      paused: '중단',
      completed: '완료',
      archived: '보관'
    },
    eventKind: {
      education: '교육',
      employment: '경력',
      appointment: '직책',
      research: '연구',
      project: '프로젝트',
      publication: '출판',
      presentation: '발표',
      award: '수상',
      release: '릴리스',
      milestone: '마일스톤',
      other: '기타'
    },
    outputKind: {
      paper: '논문',
      software: '소프트웨어',
      release: '릴리스',
      presentation: '발표',
      poster: '포스터',
      dataset: '데이터셋',
      article: '글',
      award: '수상',
      other: '기타'
    },
    relation: {
      background: '배경 지식',
      applied: '적용한 지식',
      produced: '과정에서 만든 지식',
      documents: '작업을 설명하는 지식'
    }
  },
  en: {
    personalRecord: 'Personal record',
    timeline: 'Timeline',
    projects: 'Projects',
    outputs: 'Outputs',
    knowledge: 'Knowledge',
    skipToContent: 'Skip to content',
    primaryNavigation: 'Primary navigation',
    languageSelection: 'Language selection',
    homeEyebrow: 'PERSONAL RECORD',
    now: 'Now',
    selectedProjects: 'Selected projects',
    recentOutputs: 'Recent outputs',
    allTimeline: 'Full timeline',
    allProjects: 'All projects',
    allOutputs: 'All outputs',
    timelineDescription: 'A verified chronology of roles, work, and activity.',
    projectsDescription: 'Selected work with a confirmed role, process, and outcome.',
    outputsDescription: 'Concrete results such as software, papers, and presentations.',
    knowledgeTitle: 'Explanations and study notes live in Tokamak.',
    knowledgeDescription:
      'This site records what a project did; Tokamak holds the durable knowledge developed along the way.',
    visitKnowledge: 'Explore knowledge in Tokamak',
    role: 'Role',
    contributions: 'Contributions',
    outcomes: 'Outcomes',
    relatedOutputs: 'Related outputs',
    relatedTimeline: 'Related timeline',
    relatedKnowledge: 'Related knowledge · Tokamak',
    atAGlance: 'At a glance',
    period: 'Period',
    status: 'Status',
    present: 'Present',
    sourceLanguage: 'Source',
    openProject: 'View project',
    externalLink: 'External link',
    profileApprovalRequired: 'Personal content approval is required.',
    profileApprovalDescription:
      'The structure and validators are ready, but unconfirmed history and projects are not published.',
    backToProjects: 'Back to projects',
    noPublishedProjects: 'No projects have been approved for publication.',
    noPublishedTimeline: 'No timeline records have been approved for publication.',
    noPublishedOutputs: 'No outputs have been approved for publication.',
    servedThrough: 'Static site on GitHub Pages',
    lifecycle: {
      planned: 'Planned',
      active: 'Active',
      paused: 'Paused',
      completed: 'Completed',
      archived: 'Archived'
    },
    eventKind: {
      education: 'Education',
      employment: 'Employment',
      appointment: 'Appointment',
      research: 'Research',
      project: 'Project',
      publication: 'Publication',
      presentation: 'Presentation',
      award: 'Award',
      release: 'Release',
      milestone: 'Milestone',
      other: 'Other'
    },
    outputKind: {
      paper: 'Papers',
      software: 'Software',
      release: 'Releases',
      presentation: 'Presentations',
      poster: 'Posters',
      dataset: 'Datasets',
      article: 'Articles',
      award: 'Awards',
      other: 'Other'
    },
    relation: {
      background: 'Background',
      applied: 'Applied knowledge',
      produced: 'Knowledge produced',
      documents: 'Documents this work'
    }
  }
} as const satisfies Record<Locale, object>;
